feat: Add project_id input for Google Auth Token action
Seeing these messages starting 2026-02-03

⚠️ Failed to compute a project ID from the given inputs. Neither the "project_id" output nor any environment variables will be exported. If you require these values in other steps, specify the "project_id" input directly.
Error: google-github-actions/auth failed with: failed to generate Google Cloud federated token for //iam.googleapis.com/***: {"error":"invalid_request","error_description":"Invalid value for \"audience\". This value should be the full resource name of the Identity Provider. See https://cloud.google.com/iam/docs/reference/sts/rest/v1/TopLevel/token for the list of possible formats."}